openapi: 3.0.3
info:
  title: IDC Provider API
  description: |-
    IDC(온프레미스) Provider 전용 설치 상태 관리, 방화벽 확인, 리소스 관리를 위한 API입니다.

    ### [주의 사항: Forward Compatibility]
    본 API의 모든 응답 모델은 향후 확장될 수 있습니다. 클라이언트(또는 AI Agent)는 정의되지 않은 필드가 응답에 포함되더라도 에러를 발생시키지 않고 무시해야 합니다.
  version: 1.0.0
servers:
  - url: /api/v1
    description: API Gateway Base Path

paths:
  '/idc/source-ip-recommendation':
    get:
      tags:
        - IDC Firewall
      summary: 방화벽 Source IP 추천 조회
      operationId: getIdcSourceIpRecommendation
      x-expected-duration: "50ms"
      description: |-
        **동기 작업(Synchronous)**
        IP 타입(public/private/vpc)에 따른 BDC 서버 Source IP 추천 목록을 조회합니다.
      parameters:
        - name: ipType
          in: query
          required: true
          description: "IP 타입"
          schema:
            type: string
            enum: [public, private, vpc]
      responses:
        '200':
          description: 조회 성공
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SourceIpRecommendation'
        '400':
          description: "유효하지 않은 IP 타입"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          $ref: '#/components/responses/Unauthorized'

  '/idc/target-sources/{targetSourceId}/installation-status':
    parameters:
      - $ref: '#/components/parameters/targetSourceId'
    get:
      tags:
        - IDC Installation
      summary: IDC 설치 상태 조회
      operationId: getIdcInstallationStatus
      x-expected-duration: "200ms ~ 1s"
      description: |-
        **동기 작업(Synchronous)**
        IDC BDC TF 설치 상태 및 방화벽 오픈 여부를 조회합니다.
        캐시된 상태가 있으면 캐시를 반환합니다.
      responses:
        '200':
          description: 조회 성공
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IdcInstallationStatus'
        '400':
          description: "IDC 프로젝트가 아님"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '403':
          $ref: '#/components/responses/PermissionDenied'
        '404':
          $ref: '#/components/responses/TargetSourceNotFound'

  '/idc/target-sources/{targetSourceId}/check-installation':
    parameters:
      - $ref: '#/components/parameters/targetSourceId'
    post:
      tags:
        - IDC Installation
      summary: IDC 설치 상태 실시간 동기화
      operationId: refreshIdcInstallationStatus
      x-expected-duration: "1s ~ 30s"
      description: |-
        **동기 작업(Synchronous)**
        캐시를 삭제하고 IDC 인프라 상태를 직접 확인하여 설치 상태를 강제로 갱신합니다.
      responses:
        '200':
          description: 동기화 완료
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IdcInstallationStatus'
        '400':
          description: "IDC 프로젝트가 아님"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '403':
          $ref: '#/components/responses/PermissionDenied'
        '404':
          $ref: '#/components/responses/TargetSourceNotFound'

  '/idc/target-sources/{targetSourceId}/confirm-firewall':
    parameters:
      - $ref: '#/components/parameters/targetSourceId'
    post:
      tags:
        - IDC Firewall
      summary: 방화벽 오픈 확인
      operationId: confirmIdcFirewall
      x-expected-duration: "200ms"
      description: |-
        **동기 작업(Synchronous)**
        서비스 담당자가 방화벽 오픈을 완료한 후 호출합니다.
        설치 상태의 `firewallOpened`를 `true`로 갱신합니다.
      responses:
        '200':
          description: 확인 완료
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConfirmFirewallResponse'
        '400':
          description: "IDC 프로젝트가 아님"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '403':
          $ref: '#/components/responses/PermissionDenied'
        '404':
          $ref: '#/components/responses/TargetSourceNotFound'

  '/idc/target-sources/{targetSourceId}/resources':
    parameters:
      - $ref: '#/components/parameters/targetSourceId'
    get:
      tags:
        - IDC Resources
      summary: IDC 리소스 목록 조회
      operationId: getIdcResources
      x-expected-duration: "100ms"
      description: |-
        **동기 작업(Synchronous)**
        임시 저장된 IDC 리소스 입력 목록을 조회합니다.
      responses:
        '200':
          description: 조회 성공
          content:
            application/json:
              schema:
                type: object
                required: [resources]
                properties:
                  resources:
                    type: array
                    items:
                      $ref: '#/components/schemas/IdcResourceInput'
        '400':
          description: "IDC 프로젝트가 아님"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '403':
          $ref: '#/components/responses/PermissionDenied'
        '404':
          $ref: '#/components/responses/TargetSourceNotFound'
    put:
      tags:
        - IDC Resources
      summary: IDC 리소스 임시 저장
      operationId: updateIdcResources
      x-expected-duration: "200ms"
      description: |-
        **동기 작업(Synchronous)**
        IDC 리소스 입력 목록을 임시 저장합니다.
        프로젝트 리소스에는 반영되지 않으며, confirm-targets 호출 시 확정됩니다.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [resources]
              properties:
                resources:
                  type: array
                  minItems: 1
                  items:
                    $ref: '#/components/schemas/IdcResourceInput'
      responses:
        '200':
          description: 저장 성공
          content:
            application/json:
              schema:
                type: object
                required: [resources]
                properties:
                  resources:
                    type: array
                    items:
                      $ref: '#/components/schemas/IdcResourceInput'
        '400':
          description: "유효성 검증 실패 또는 IDC 프로젝트가 아님"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '403':
          $ref: '#/components/responses/PermissionDenied'
        '404':
          $ref: '#/components/responses/TargetSourceNotFound'

  '/idc/target-sources/{targetSourceId}/resources/list':
    parameters:
      - $ref: '#/components/parameters/targetSourceId'
    put:
      tags:
        - IDC Resources
      summary: IDC 리소스 목록 갱신 (기존 유지 + 신규 추가)
      operationId: updateIdcResourcesList
      x-expected-duration: "300ms"
      description: |-
        **동기 작업(Synchronous)**
        기존 리소스 중 유지할 ID 목록과 신규 리소스를 받아 프로젝트 리소스를 갱신합니다.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                keepResourceIds:
                  type: array
                  description: "유지할 기존 리소스 ID 목록"
                  items:
                    type: string
                newResources:
                  type: array
                  description: "신규 추가할 리소스 목록"
                  items:
                    $ref: '#/components/schemas/IdcResourceInput'
      responses:
        '200':
          description: 갱신 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  project:
                    type: object
                    description: "업데이트된 프로젝트 정보 (Forward Compatibility)"
        '400':
          description: "유효성 검증 실패"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '403':
          $ref: '#/components/responses/PermissionDenied'
        '404':
          $ref: '#/components/responses/TargetSourceNotFound'

  '/idc/target-sources/{targetSourceId}/confirm-targets':
    parameters:
      - $ref: '#/components/parameters/targetSourceId'
    post:
      tags:
        - IDC Resources
      summary: IDC 연동 대상 확정
      operationId: confirmIdcTargets
      x-expected-duration: "500ms"
      description: |-
        **동기 작업(Synchronous)**
        리소스를 프로젝트에 추가하고 설치 단계(INSTALLING)로 전이합니다.
        설치 상태가 PENDING으로 초기화됩니다.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [resources]
              properties:
                resources:
                  type: array
                  minItems: 1
                  items:
                    $ref: '#/components/schemas/IdcResourceInput'
      responses:
        '200':
          description: 확정 성공
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConfirmTargetsResponse'
        '400':
          description: "유효성 검증 실패 또는 IDC 프로젝트가 아님"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '403':
          $ref: '#/components/responses/PermissionDenied'
        '404':
          $ref: '#/components/responses/TargetSourceNotFound'

components:
  parameters:
    targetSourceId:
      name: targetSourceId
      in: path
      required: true
      description: "타겟 소스 고유 식별자"
      schema:
        type: integer

  schemas:
    IdcInstallationStatus:
      type: object
      description: "IDC 설치 상태"
      required: [provider, bdcTf, firewallOpened]
      properties:
        provider:
          type: string
          enum: [IDC]
        bdcTf:
          type: string
          enum: [PENDING, IN_PROGRESS, COMPLETED, FAILED]
          description: "BDC Terraform 설치 상태"
        firewallOpened:
          type: boolean
          description: "방화벽 오픈 여부"
        lastCheckedAt:
          type: string
          format: date-time
          description: "마지막 확인 시각"
        error:
          type: object
          description: "에러 정보 (실패 시)"
          properties:
            code:
              type: string
            message:
              type: string

    SourceIpRecommendation:
      type: object
      description: "Source IP 추천 정보"
      required: [sourceIps, port, description]
      properties:
        sourceIps:
          type: array
          items:
            type: string
          description: "추천 Source IP 목록"
        port:
          type: integer
          description: "추천 포트"
        description:
          type: string
          description: "설명"

    ConfirmFirewallResponse:
      type: object
      description: "방화벽 확인 응답"
      required: [confirmed, confirmedAt]
      properties:
        confirmed:
          type: boolean
        confirmedAt:
          type: string
          format: date-time

    IdcResourceInput:
      type: object
      description: "IDC 리소스 입력 정보"
      required: [name, inputFormat, port, databaseType]
      properties:
        name:
          type: string
          description: "리소스 이름"
        inputFormat:
          type: string
          enum: [IP, HOST]
          description: "입력 형식"
        ips:
          type: array
          maxItems: 3
          items:
            type: string
          description: "IP 목록 (inputFormat=IP일 때)"
        host:
          type: string
          maxLength: 100
          description: "호스트명 (inputFormat=HOST일 때)"
        port:
          type: integer
          description: "포트 번호"
        databaseType:
          type: string
          enum: [ORACLE, MYSQL, POSTGRESQL, MSSQL]
          description: "데이터베이스 타입"
        serviceId:
          type: string
          description: "Oracle Service ID (Oracle 필수)"
        credentialId:
          type: string
          description: "선택된 Credential ID"

    ConfirmTargetsResponse:
      type: object
      description: "연동 대상 확정 응답"
      required: [confirmed, confirmedAt]
      properties:
        confirmed:
          type: boolean
        confirmedAt:
          type: string
          format: date-time
        project:
          type: object
          description: "업데이트된 프로젝트 정보 (Forward Compatibility)"

    ErrorResponse:
      type: object
      description: "에러 응답 공통 모델"
      required: [error]
      properties:
        error:
          type: object
          required: [code, message]
          properties:
            code:
              type: string
              description: "에러 코드"
            message:
              type: string
              description: "에러 상세 메시지"

  responses:
    Unauthorized:
      description: "인증 실패"
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
          example:
            error:
              code: "UNAUTHORIZED"
              message: "인증이 필요합니다."

    PermissionDenied:
      description: "인가 실패 (API 호출 권한 없음)"
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
          example:
            error:
              code: "FORBIDDEN"
              message: "해당 리소스에 접근할 권한이 없습니다."

    TargetSourceNotFound:
      description: "대상 소스를 찾을 수 없음"
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
          example:
            error:
              code: "TARGET_SOURCE_NOT_FOUND"
              message: "요청하신 Target Source를 찾을 수 없습니다."
