openapi: 3.0.3
info:
  title: Cloud Resource Scan API
  description: |-
    AWS, Azure, GCP 리소스 스캔을 위한 통합 API 명세서입니다.
    
    ### [주의 사항: Forward Compatibility]
    본 API의 모든 응답 모델은 향후 확장될 수 있습니다. 클라이언트(또는 AI Agent)는 **정의되지 않은 필드가 응답에 포함되더라도 에러를 발생시키지 않고 무시(Ignore unknown fields)**해야 합니다.
    
    ### 주요 특징
    * **멀티 클라우드 지원**: AWS, Azure, GCP의 다양한 리소스 타입을 지원합니다.
    * **비동기 처리**: 스캔 시작은 비동기 방식으로 동작하며, 폴링을 통해 상태를 확인해야 합니다.
  version: 1.1.0
servers:
  - url: /api/v1
    description: 기본 API 경로

paths:
  /target-sources/{targetSourceId}/scan:
    post:
      summary: 스캔 실행 (비동기)
      operationId: startScan
      x-expected-duration: "30s ~ 5m"
      x-polling-interval: "5s"
      description: |-
        특정 Target Source에 대해 클라우드 리소스 스캔을 시작합니다.
        
        * **비동기 작업**: 요청 즉시 `202 Accepted`를 반환하며 실제 스캔은 백그라운드에서 진행됩니다.
        * **중복 방지**: 이미 진행 중인 스캔이 있을 경우 `409 Conflict`를 반환합니다.
        * ** Timeout**: 스캔을 수행한지 30분 이상 소요되는 경우엔 TIMEOUT로 변경됩니다.
      parameters:
        - name: targetSourceId
          in: path
          required: true
          schema:
            type: integer
          example: 101
      responses:
        '202':
          description: 스캔 요청 수락됨
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ScanJob'
        '404':
          description: Target Source를 찾을 수 없음
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                error:
                  code: "TARGET_SOURCE_NOT_FOUND"
                  message: "요청하신 Target Source를 찾을 수 없습니다."
        '409':
          description: 이미 해당 소스에 대해 진행 중인 스캔 작업이 존재함
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                error:
                  code: "CONFLICT_IN_PROGRESS"
                  message: "현재 스캔이 진행 중입니다."

  /target-sources/{targetSourceId}/scanJob/latest:
    get:
      summary: 현재 스캔 상태 조회
      operationId: getLatestScanJob
      x-expected-duration: "50ms"
      description: |-
        해당 Target Source의 가장 최근 스캔 작업 상태를 조회합니다.
        폴링 방식으로 스캔 완료 여부를 확인할 때 사용합니다.
      parameters:
        - name: targetSourceId
          in: path
          required: true
          schema:
            type: integer
          example: 101
      responses:
        '200':
          description: 성공
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ScanJob'
        '404':
          description: Target Source를 찾을 수 없거나, Scan작업이 한번도 동작한 적 없음.

  /target-sources/{targetSourceId}/scan/history:
    get:
      summary: 스캔 이력 조회
      operationId: getScanHistory
      description: |-
        Target Source 내에서 발생한 스캔 이력을 요약된 페이지네이션 정보와 함께 조회합니다.
      parameters:
        - name: targetSourceId
          in: path
          required: true
          schema:
            type: integer
          example: 50
        - name: page
          in: query
          schema:
            type: integer
            default: 0
          description: 페이지 번호 (0부터 시작)
        - name: size
          in: query
          schema:
            type: integer
            default: 10
          description: 페이지 당 항목 수
      responses:
        '200':
          description: 성공
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ScanHistoryResponse'
        '404':
          description: Target Source를 찾을 수 없음.

components:
  schemas:
    ScanStatus:
      type: string
      enum: [SCANNING, FAIL, CANCELED, SUCCESS, TIMEOUT]
      description: 스캔의 현재 상태
      example: "SCANNING"

    ScanJob:
      type: object
      description: 스캔 작업의 상세 정보입니다. 명세에 없는 필드가 추가될 수 있으므로 유연하게 처리하십시오.
      properties:
        id:
          type: integer
          format: int64
          example: 12345
        scanStatus:
          $ref: '#/components/schemas/ScanStatus'
        targetSourceId:
          type: integer
          example: 101
        createdAt:
          type: string
          format: date-time
          example: "2026-02-12T05:42:47.581Z"
        updatedAt:
          type: string
          format: date-time
          example: "2026-02-12T05:42:47.581Z"
        scanVersion:
          type: integer
          description: 스캔 차수
          example: 1
        scanProgress:
          type: integer
          nullable: true
          description: 스캔 진행률 (현재 미지원으로 항상 null)
          example: null
        durationSeconds:
          type: integer
          description: 소요 시간(초). SUCCESS/FAIL 종료 시에만 값이 업데이트됩니다.
          example: 120
        resourceCountByResourceType:
          type: object
          additionalProperties:
            type: integer
          description: 리소스 타입별 탐지된 개수 (Key는 RESOURCE_TYPE Enum 참조)
          example:
            AWS_EC2_INSTANCE: 5
            GCP_SQL: 1
        scanError:
          type: string
          nullable: true
          description: "에러 발생 시 에러 코드 (예: AUTH_PERMISSION_ERROR)"
          example: null

    ScanHistoryResponse:
      type: object
      description: 스캔 이력 조회 응답 (데이터 목록과 최소한의 페이지 정보만 포함)
      properties:
        content:
          type: array
          description: 스캔 이력 리스트
          items:
            $ref: '#/components/schemas/ScanJob'
        page:
          $ref: '#/components/schemas/PageInfo'

    PageInfo:
      type: object
      description: 페이지네이션 메타데이터
      properties:
        totalElements:
          type: integer
          description: 전체 항목 개수
          example: 15
        totalPages:
          type: integer
          description: 전체 페이지 개수
          example: 2
        number:
          type: integer
          description: 현재 페이지 번호 (0-based)
          example: 0
        size:
          type: integer
          description: 요청한 페이지 당 항목 수
          example: 10
    ErrorResponse:
      type: object
      required: [error]
      properties:
        error:
          type: object
          required: [code, message]
          properties:
            code:
              type: string
              example: "CONFLICT_IN_PROGRESS"
            message:
              type: string
              example: "현재 스캔이 진행 중입니다."
