-- ADR-016 V1 — canonical Postgres schema (migrations.md). Reference DDL: prod applies this (ddl-auto=validate);
-- tests use H2 with Hibernate auto-DDL. Instants are timestamptz; Durations are stored as bigint nanoseconds
-- (Hibernate's default Duration mapping); payload/spec hold JSON as text (the entities map them as String, so
-- the column type must be text/varchar for ddl-auto=validate, not jsonb). Enums are text (@Enumerated STRING).

CREATE TABLE pipeline (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    target_source_id       TEXT        NOT NULL,
    type                   TEXT        NOT NULL,   -- INSTALL | DELETE
    provider               TEXT        NOT NULL,
    status                 TEXT        NOT NULL,   -- RUNNING | CANCELLING | DONE | FAILED | CANCELLED
    triggered_by           TEXT        NOT NULL,   -- HUMAN | SYSTEM | AI
    created_at             TIMESTAMPTZ,
    started_at             TIMESTAMPTZ,
    finished_at            TIMESTAMPTZ,
    last_activity_at       TIMESTAMPTZ,
    fail_reason_task_id    BIGINT,
    fail_reason_error_code TEXT,
    version                BIGINT,
    -- "one non-terminal run per target" (Decision 5): a generated column = target while non-terminal, NULL once
    -- terminal; UNIQUE admits many terminal rows (NULL) but at most one active per target. Equivalent to the
    -- partial index `CREATE UNIQUE INDEX ... (target_source_id) WHERE status NOT IN ('DONE','FAILED','CANCELLED')`.
    active_target_source_id TEXT GENERATED ALWAYS AS (
        CASE WHEN status IN ('DONE','FAILED','CANCELLED') THEN NULL ELSE target_source_id END) STORED,
    CONSTRAINT uq_pipeline_active_target UNIQUE (active_target_source_id)
);
CREATE INDEX ix_pipeline_target_started ON pipeline (target_source_id, started_at);
CREATE INDEX ix_pipeline_started        ON pipeline (started_at);
CREATE INDEX ix_pipeline_last_activity  ON pipeline (last_activity_at);

CREATE TABLE task (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pipeline_id       BIGINT  NOT NULL,
    seq               INT     NOT NULL,
    name              TEXT    NOT NULL,
    handler_key       TEXT    NOT NULL,
    kind              TEXT    NOT NULL,   -- TERRAFORM_JOB | CONDITION_CHECK
    status            TEXT    NOT NULL,   -- BLOCKED | READY | DISPATCHING | RUNNING | WAITING_EXTERNAL | DONE | FAILED | EXPIRED | CANCELLED
    polling_interval  BIGINT,            -- frozen knobs (nanoseconds); null = global default
    ttl               BIGINT,
    execution_timeout BIGINT,
    max_fail_count    INT     NOT NULL,
    fail_count        INT     NOT NULL,
    next_check_at     TIMESTAMPTZ,
    last_checked_at   TIMESTAMPTZ,
    deadline_at       TIMESTAMPTZ,
    started_at        TIMESTAMPTZ,
    finished_at       TIMESTAMPTZ,
    version           BIGINT,
    CONSTRAINT uq_task_pipeline_seq UNIQUE (pipeline_id, seq)
);
CREATE INDEX ix_task_pipeline_seq ON task (pipeline_id, seq);
-- queue-wait / due selection support
CREATE INDEX ix_task_kind_status  ON task (kind, status);
CREATE INDEX ix_task_next_check    ON task (next_check_at, last_checked_at);

CREATE TABLE task_attempt (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id     BIGINT NOT NULL,
    attempt_no  INT    NOT NULL,
    started_at  TIMESTAMPTZ,
    finished_at TIMESTAMPTZ,
    response    TEXT,                     -- dispatch output {jobId} (write-once)
    error_detail TEXT,
    error_code  TEXT,                     -- bucket ①: EXECUTION_TIMEOUT | DISPATCH_NO_RESPONSE | IM_REJECTED | JOB_FAILED
    result      TEXT                      -- OK | FAIL (terminal)
);
CREATE INDEX ix_attempt_task ON task_attempt (task_id, attempt_no);
-- WORKER_OUTAGE alert support
CREATE INDEX ix_attempt_timeout ON task_attempt (error_code, finished_at);

CREATE TABLE task_check (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id         BIGINT NOT NULL,
    started_at      TIMESTAMPTZ,
    checked_at      TIMESTAMPTZ,
    poll_count      INT    NOT NULL,
    kind            TEXT   NOT NULL,      -- DISPATCH | CHECK
    name            TEXT   NOT NULL,
    api_result      TEXT   NOT NULL,      -- PENDING | OK | ERROR
    observed        TEXT,                 -- RUNNING | SUCCEEDED | FAILED | MET | NOT_MET
    error_code      TEXT,                 -- bucket ②: CHECK_ERROR | CALL_TIMEOUT (+ synthetic HANDLER_NOT_FOUND)
    latency_ms      BIGINT,
    external_handle TEXT
);
CREATE INDEX ix_check_task_started ON task_check (task_id, started_at);
-- RLE open-run lookup partition + retention prune support
CREATE INDEX ix_check_partition ON task_check (task_id, kind, name, external_handle, started_at DESC, id DESC);
CREATE INDEX ix_check_checked_at ON task_check (checked_at);

CREATE TABLE pipeline_event (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pipeline_id BIGINT,                   -- null for global events (settings, alerts)
    task_id     BIGINT,
    type        TEXT NOT NULL,
    severity    TEXT NOT NULL,            -- INFO | CRITICAL
    payload     TEXT,                     -- JSON rendered to the API `message` (entity maps it as String)
    actor       TEXT NOT NULL,
    created_at  TIMESTAMPTZ NOT NULL,
    notified_at TIMESTAMPTZ               -- Notifier outbox cursor: NULL = unsent
);
CREATE INDEX ix_event_pipeline_created ON pipeline_event (pipeline_id, created_at);
-- outbox claim (FOR UPDATE SKIP LOCKED over unsent) + alert dedup (type, created_at)
CREATE INDEX ix_event_unsent ON pipeline_event (created_at) WHERE notified_at IS NULL;
CREATE INDEX ix_event_type_created ON pipeline_event (type, created_at);

CREATE TABLE pipeline_def_snapshot (
    pipeline_id        BIGINT PRIMARY KEY,   -- 1:1, write-once
    definition_key     TEXT  NOT NULL,
    definition_version TEXT  NOT NULL,
    type               TEXT  NOT NULL,
    provider           TEXT  NOT NULL,
    spec               TEXT  NOT NULL        -- resolved recipe JSON (snake_case keys, ADR-019; String-mapped)
);

CREATE TABLE setting (
    setting_key   TEXT PRIMARY KEY,
    setting_value TEXT NOT NULL
);
