/**
 * Backend contract snapshot supplied on 2026-09-06: BFF 13, Infra 67, Jira 2.
 * Upstream revision/deployment and the remaining Jira/Orchestration codes are unverified.
 * See docs/bff-api/catalogs/error-codes.md for sources and occurrence groups.
 *
 * Values are expected HTTP statuses for contract checks, never response overrides.
 * Registration does not enable UI handling: AppErrorCode, fetchJson and route error
 * normalization deliberately remain separate until the next implementation phase.
 */
export const BACKEND_ERROR_CODES = Object.freeze({
  // BFF: the supplied table has 13 rows despite its "12 codes" heading.
  BFF_REQUEST_INVALID: 400,
  BFF_GUIDE_CONTENT_INVALID: 400,
  BFF_AUTHENTICATION_FAILED: 401,
  BFF_ACCESS_DENIED: 403,
  BFF_APPROVAL_REQUEST_NOT_FOUND: 404,
  BFF_SERVICE_NOT_FOUND: 404,
  BFF_USER_NOT_FOUND: 404,
  BFF_PERMISSION_REQUEST_NOT_FOUND: 404,
  BFF_TARGET_SOURCE_ALREADY_EXISTS: 409,
  BFF_TARGET_SOURCE_CLOUD_PROVIDER_MISMATCH: 400,
  BFF_UPSTREAM_AUTH_FAILED: 502,
  BFF_UPSTREAM_UNAVAILABLE: 502,
  BFF_UPSTREAM_TIMEOUT: 504,

  // Infra A.1: approval, target source and common input (17).
  INFRA_APPROVAL_REQUEST_NOT_FOUND: 404,
  INFRA_APPROVAL_STATUS_INVALID: 400,
  INFRA_APPROVAL_REQUEST_CONFLICT: 409,
  INFRA_TARGET_SOURCE_NOT_FOUND: 404,
  INFRA_TARGET_SOURCE_ALREADY_EXISTS: 409,
  INFRA_TARGET_SOURCE_CLOUD_PROVIDER_INVALID: 400,
  INFRA_SERVICE_NOT_FOUND: 404,
  INFRA_REQUEST_INVALID: 400,
  INFRA_AGENT_ID_INVALID: 400,
  INFRA_SERVICE_CODE_INVALID: 400,
  INFRA_DATABASE_TYPE_INVALID: 400,
  INFRA_DATA_INVALID: 400,
  INFRA_RESOURCE_NOT_FOUND: 404,
  INFRA_RESOURCE_ALREADY_EXISTS: 409,
  INFRA_RESOURCE_ID_MISMATCH: 400,
  INFRA_CREDENTIAL_NOT_FOUND: 400,
  INFRA_OPERATION_NOT_SUPPORTED: 501,

  // Infra A.2: scan and test connection (10).
  INFRA_SCAN_DATA_OLD_VERSION: 400,
  INFRA_SCAN_IN_PROGRESS: 409,
  INFRA_SCAN_FAILED: 403,
  INFRA_SCAN_NOT_EXECUTED: 404,
  INFRA_TEST_CONNECTION_IN_PROGRESS: 409,
  INFRA_TEST_CONNECTION_NO_SUCCESS: 404,
  INFRA_CLUSTER_CREATION_IN_PROGRESS: 409,
  INFRA_CONFIRMED_INFRA_NOT_FOUND: 404,
  INFRA_INTEGRATED_RESULT_NOT_FOUND: 404,
  INFRA_DATA_INCONSISTENCY: 500,

  // Infra A.3: cloud providers and Kubernetes (22).
  INFRA_AWS_TARGET_NOT_INITIALIZED: 425,
  INFRA_AWS_TARGET_UNAVAILABLE: 503,
  INFRA_AWS_TARGET_UNHEALTHY: 502,
  INFRA_AWS_ROLE_NOT_FOUND: 404,
  INFRA_AWS_AUTH_FAILED: 403,
  INFRA_AWS_ASSUME_ROLE_FAILED: 500,
  INFRA_AWS_API_FAILED: 500,
  INFRA_AWS_SDK_CLIENT_UNAVAILABLE: 503,
  INFRA_ATHENA_QUERY_FAILED: 500,
  INFRA_BDC_ROLE_AUTH_FAILED: 500,
  INFRA_AZURE_HEALTH_CHECK_FAILED: 502,
  INFRA_AZURE_VM_SUBNET_NOT_FOUND: 400,
  INFRA_GCP_IO_API_FAILED: 500,
  INFRA_GCP_OAUTH_FAILED: 409,
  INFRA_GCP_PROJECT_ID_NOT_FOUND: 404,
  INFRA_GCP_REGIONAL_SUBNET_NOT_FOUND: 400,
  INFRA_GCP_VPC_SERVICE_CONTROLS_VIOLATION: 403,
  INFRA_GCP_PSC_NOT_APPROVED: 400,
  INFRA_GCP_RECOMMENDATION_HAS_ERROR: 400,
  INFRA_GCP_TERRAFORM_RECHECK_REQUIRED: 404,
  INFRA_KUBERNETES_SPECIFICATION_INVALID: 500,
  INFRA_KUBERNETES_API_FAILED: 500,

  // Infra A.4: Terraform, recommendation and other operations (18).
  INFRA_TERRAFORM_SCRIPT_NOT_FOUND: 404,
  INFRA_TERRAFORM_TYPE_MISMATCH: 422,
  INFRA_TERRAFORM_WORKER_IN_PROGRESS: 503,
  INFRA_TERRAFORM_DEPENDENCY_IN_PROGRESS: 409,
  INFRA_CIDR_SPACE_UNAVAILABLE: 409,
  INFRA_CIDR_RECOMMENDATION_FAILED: 409,
  INFRA_NLB_INDEX_NOT_ASSIGNED: 400,
  INFRA_NLB_INDEX_NOT_FOUND: 400,
  INFRA_GCS_URI_INVALID: 400,
  INFRA_PHASE_INVALID: 400,
  INFRA_JSON_PARSING_FAILED: 400,
  INFRA_DATABASE_HOST_INVALID: 400,
  INFRA_UTILITY_CLASS_INSTANTIATION_INVALID: 400,
  INFRA_BUCKET_NOT_FOUND: 404,
  INFRA_CLOUD_FUNCTION_FAILED: 409,
  INFRA_CSS_LOADING_FAILED: 500,
  INFRA_UPDATE_FAILED: 500,
  INFRA_AGENT_ID_ALREADY_EXISTS: 409,

  // Jira: only these two of the reported eight enum members were supplied.
  JIRA_TICKET_NOT_FOUND: 404,
  JIRA_USER_NOT_FOUND: 404,
} as const);

export type BackendErrorCode = keyof typeof BACKEND_ERROR_CODES;

/** Recognize exact registered codes, not prefixes, aliases or inherited keys. */
export function isBackendErrorCode(value: unknown): value is BackendErrorCode {
  return typeof value === 'string'
    && Object.prototype.hasOwnProperty.call(BACKEND_ERROR_CODES, value);
}
