#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat <<'EOF'
Usage:
  bash scripts/pr-flow.sh [--base main] [--strategy squid] [--title "title"] [--body "body"] [--merge-approved]

Options:
  --base       Base branch (default: main)
  --strategy   merge | squash | squid (default: squid)
  --title      PR title (default: last commit subject)
  --body       PR body (default: generated by scripts/build-pr-body.sh)
  --merge-approved  Legacy compatibility only. Prefer /pr-merge for merge.
EOF
}

BASE_BRANCH="main"
STRATEGY="squid"
TITLE=""
BODY=""
MERGE_APPROVED="0"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --base)
      BASE_BRANCH="${2:-}"
      shift 2
      ;;
    --strategy)
      STRATEGY="${2:-}"
      shift 2
      ;;
    --title)
      TITLE="${2:-}"
      shift 2
      ;;
    --body)
      BODY="${2:-}"
      shift 2
      ;;
    --merge-approved)
      MERGE_APPROVED="1"
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "[pr-flow] Unknown argument: $1" >&2
      usage
      exit 1
      ;;
  esac
done

case "${STRATEGY}" in
  merge) MERGE_METHOD="merge" ;;
  squash|squid) MERGE_METHOD="squash" ;;
  *)
    echo "[pr-flow] Invalid strategy: ${STRATEGY}" >&2
    exit 1
    ;;
esac

repo_root="$(git rev-parse --show-toplevel)"
cd "${repo_root}"

bash scripts/pr-check.sh --base "${BASE_BRANCH}"

branch="$(git rev-parse --abbrev-ref HEAD)"
log_branch="${branch//\//-}"
LOG_DIR="${TMPDIR:-/tmp}/pii-agent-demo-pr-flow-${log_branch}-$$"
mkdir -p "${LOG_DIR}"
STEP_COUNT=0

run_logged() {
  local label="$1"
  shift

  STEP_COUNT=$((STEP_COUNT + 1))
  local log_file="${LOG_DIR}/step-${STEP_COUNT}.log"

  if "$@" >"${log_file}" 2>&1; then
    return 0
  fi

  echo "[pr-flow] ${label}: FAILED" >&2
  echo "[pr-flow] Last log lines (${log_file}):" >&2
  tail -80 "${log_file}" >&2 || true
  exit 1
}

marker_file="$(git rev-parse --git-path pii-pr-validation.env)"
summary_file="$(git rev-parse --git-path pii-pr-validation-summary.md)"
commit_count="$(sed -n 's/^commitCount=//p' "${marker_file}" | tail -1)"
check_log_dir="$(sed -n 's/^logDir=//p' "${marker_file}" | tail -1)"
validation_summary="$(sed -n '1,200p' "${summary_file}" 2>/dev/null || true)"

run_logged "push" git push -u origin "${branch}" --force-with-lease

pr_number="$(gh pr list --head "${branch}" --base "${BASE_BRANCH}" --state open --json number --jq '.[0].number' || true)"

if [[ -z "${pr_number}" || "${pr_number}" == "null" ]]; then
  if [[ -z "${TITLE}" ]]; then
    TITLE="$(git log -1 --pretty=%s)"
  fi
  if [[ -z "${BODY}" ]]; then
    BODY="$(PII_PR_VALIDATION="${validation_summary}" bash scripts/build-pr-body.sh --base "${BASE_BRANCH}")"
  fi

  echo "[pr-flow] Creating PR -> base:${BASE_BRANCH}, head:${branch}"
  gh pr create --base "${BASE_BRANCH}" --head "${branch}" --title "${TITLE}" --body "${BODY}" >/dev/null
  pr_number="$(gh pr list --head "${branch}" --base "${BASE_BRANCH}" --state open --json number --jq '.[0].number')"
fi

pr_url="$(gh pr view "${pr_number}" --json url --jq .url)"
echo "[pr-flow] PR ready: ${pr_url}"
echo "[pr-flow] Commits: ${commit_count}"
echo "[pr-flow] Validation: PASS"
echo "[pr-flow] Logs: ${check_log_dir}"

if [[ "${MERGE_APPROVED}" != "1" ]]; then
  echo "[pr-flow] Merge skipped: explicit user merge request is required."
  exit 0
fi

state="$(gh pr view "${pr_number}" --json state --jq .state)"
if [[ "${state}" != "OPEN" ]]; then
  echo "[pr-flow] PR #${pr_number} is not OPEN (state=${state})." >&2
  exit 1
fi

for _ in {1..10}; do
  mergeable="$(gh pr view "${pr_number}" --json mergeable --jq .mergeable)"
  if [[ "${mergeable}" != "UNKNOWN" ]]; then
    break
  fi
  sleep 1
done

if [[ "${mergeable}" != "MERGEABLE" ]]; then
  echo "[pr-flow] PR #${pr_number} is not mergeable (mergeable=${mergeable})." >&2
  exit 1
fi

head_sha="$(gh pr view "${pr_number}" --json headRefOid --jq .headRefOid)"
echo "[pr-flow] Merging PR #${pr_number} with method=${MERGE_METHOD} (strategy=${STRATEGY})"
gh api -X PUT "repos/:owner/:repo/pulls/${pr_number}/merge" \
  -f merge_method="${MERGE_METHOD}" \
  -f sha="${head_sha}" >/dev/null

echo "[pr-flow] Deleting remote branch: ${branch}"
git push origin --delete "${branch}" >/dev/null || true

merged_at="$(gh pr view "${pr_number}" --json mergedAt --jq .mergedAt)"
merge_commit="$(gh pr view "${pr_number}" --json mergeCommit --jq .mergeCommit.oid)"
pr_url="$(gh pr view "${pr_number}" --json url --jq .url)"

echo "[pr-flow] Done"
echo "  PR: ${pr_url}"
echo "  mergedAt: ${merged_at}"
echo "  mergeCommit: ${merge_commit}"
